name: CD Pipeline

on: 
  workflow_run: 
    workflows: ["Scan CI"]
    types: 
      - completed
        
jobs:
  deploy:
    runs-on: shoeshop_be
    env:
      CONTAINER_NAME: 'shoeshop_be'

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Delete old docker container
        run: docker rm -f $CONTAINER_NAME || true
        
      - name: Delete old image
        run: docker rmi $ECR_IMAGE_NAME || true

      - name: Docker pull
        env:
          ECR_IMAGE_NAME: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest
        run: docker pull $ECR_IMAGE_NAME
        
      - name: Run container
        env:
          ECR_IMAGE_NAME: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest
        run: docker run -e "ConnectionStrings__UserAppCon=${{secrets.DB_CONECT_STRING}}" --name $CONTAINER_NAME -dp 5214:5214 $ECR_IMAGE_NAME